spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:mysql://localhost:3306/playground?serverTimezone=UTC&characterEncoding=UTF-8 # log4jdbc:
    username: ssafy
    password: ssafy


  jpa:
    show-sq: true
    hibernate:
      ddl-auto: update # validate
    properties:
      hibernate:
        format_sql: true
