server:
  port: 443


spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      httpclient:
        ssl:
          # useInsecureTrustManager: true # SSL Route(?) 허용
          # ssl과 domain 관련(https를 사용할 경우 상대 docker container의 name 사용이 불가능한 이유, spring cloud gateway에서 라우팅이 안됨.)
          #    : https://juinthyme.tistory.com/3
          trustedX509Certificates:
            - classpath:cert1.pem

      routes:
        - id: oauth2-service
          uri: https://i8b309.p.ssafy.io:8080
          predicates:
            - Path=/oauth2/**

        - id: user-service
          uri: http://user-service:8080
          predicates:
            - Path=/user/**, /file/**
#          filters:
#            - RewritePath=/oauth/(?<path>.*),/$\{path}

        - id: matching-service
          uri: http://matching-service:8080
          predicates:
            - Path=/matching/**

        - id: notify-service
          uri: http://notify-service:8080
          predicates:
            - Path=/notify/**


        - id: react-framework
          uri: http://react-framework:3000/
          predicates:
            - Path=/playground/**
#          filters:
#            - RewritePath=/pages/(?<path>.*),/$\{path}




  data:
    redis:
      host: redis
      port: 6379

oauth2:
  client:
    registration:
      client-id:
        kakao: 79c6d214ca859ea2806d6bd426ffb1fe

#eureka:
#  client:
#    fetch-registry: true # 유레카 클라이언트 활성화
#    register-with-eureka: true # 유레카 클라이언트 활성화
#    service-url:
#      defaultZone: http://localhost:8761/eureka # 유레카 클라이언트로 등록