server:
  port: 80


spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: oauth2-service
          uri: http://localhost:443
          predicates:
            - Path=/oauth2/**

  data:
    redis:
      host: localhost
      port: 6379

oauth2:
  client:
    registration:
      client-id:
        kakao: 79c6d214ca859ea2806d6bd426ffb1fe

#eureka:
#  client:
#    fetch-registry: true # 유레카 클라이언트 활성화
#    register-with-eureka: true # 유레카 클라이언트 활성화
#    service-url:
#      defaultZone: http://localhost:8761/eureka # 유레카 클라이언트로 등록