#server:
#  port: 443

#  ssl:
#    key-store: classpath:keystore.p12
#    key-store-type: PKCS12
#    key-password: password

spring:
  application:
    name: oauth2-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # url: jdbc:mysql://localhost:3306/playground?serverTimezone=UTC&characterEncoding=UTF-8
    url: jdbc:mysql://i8b309.p.ssafy.io:3333/playground?serverTimezone=UTC&characterEncoding=UTF-8
    username: ssafy
    password: b309oo
#    password: ssafy


  jpa:
    show-sq: true
    hibernate:
      ddl-auto: update # validate
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: i8b309.p.ssafy.io # localhost
      port: 6379


oauth2:
  api_gateway_url: "https://i8b309.p.ssafy.io" # "https://localhost:8080" #
  client:
    registration:
      client-id:
        kakao: 0ec9e81052acada4b61a0e98229b431d
